clothesWebSite/Models/ProductDetail.cs
namespace clothesWebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ProductDetail")]
    public partial class ProductDetail
    {
        [Key]
        public int product_detail_id { get; set; }

        public int product_id { get; set; }

        [Required]
        [StringLength(10)]
        public string size { get; set; }

        public int color { get; set; }

        public int quantity { get; set; }

        public virtual Product Product { get; set; }
    }
}

clothesWebSite/Controllers/ClothesController.cs
using clothesWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using clothesWebSite.DAO;
using PagedList;
using PagedList.Mvc;
namespace clothesWebSite.Controllers
{
    public class ClothesController : Controller
    {
        ProductDAO productDAO = new ProductDAO();
        BannerDAO bannerDAO = new BannerDAO();
        PostDAO postDAO = new PostDAO();
        ProductTypeDAO productTypeDAO = new ProductTypeDAO();
        // GET: Clothes
        public ActionResult Index()
        {
            IEnumerable<Product> listPro = productDAO.getHotProduct(8);
            IEnumerable<Banner> listBannerTop = bannerDAO.getBannerTop();
            IEnumerable<Banner> listBannerBot = bannerDAO.getBannerBottom();
            IEnumerable<Post> listPost = postDAO.getNewPost(2);
            ViewBag.product = listPro;
            ViewBag.bannerT = listBannerTop;
            ViewBag.bannerB = listBannerBot;
            ViewBag.post = listPost;
            return View();
        }
        public ActionResult ProductDetail(int id)
        {
            Product product = productDAO.getOne(id);
            string idCategory = product.type_id;
            IEnumerable<Product> listProCate = productDAO.getSameCategory(idCategory, 3, id);
            IEnumerable<Product> listHotPro = productDAO.getHotProduct(3, id);
            ViewBag.productCate = listProCate;
            ViewBag.productHot = listHotPro;
            return View(product);
        }
        public ActionResult ProductCategoty(string id, int getType)
        {
            if (getType == 0)
            {
                IEnumerable<Product> listPro = productDAO.getSameCategory(id);
                ViewBag.listPro = listPro;
            } else
            {
                IEnumerable<Product> listPro = productDAO.getSaleProductsWithCategory(id);
                ViewBag.listPro = listPro;
            }
            
            return View();
        }
        public ActionResult AllProduct(string sort,int? page, int pageSize = 9)
        {
            int pageNum = (page ?? 1);
            int count = productDAO.ProductCount();
            ViewBag.itemshow = pageSize;
            ViewBag.sort = sort;
            IEnumerable<Product> listPro = productDAO.getList(sort,count);
            ViewBag.countAll = productDAO.ProductCount();
            return View(listPro.ToPagedList(pageNum, pageSize));
        }
        public ActionResult AllPost()
        {
            IEnumerable<Post> listPost = postDAO.getNewPost(2);
            ViewBag.listPost = listPost;
            return View();
        }
        public ActionResult PostDeitail(int id)
        {
            Post post = postDAO.getOne(id);
            return View(post);
        }

        public ActionResult ProductSale(int? page, int itemShow = 12)
        {
            IEnumerable<Product> saleProducts = productDAO.getSaleProducts();
            if (itemShow > saleProducts.Count())
            {
                itemShow = saleProducts.Count();
            }
            int pageNum = (page ?? 1);
            int pageSize = itemShow;
            ViewBag.itemShow = itemShow;
            ViewBag.itemCount = saleProducts.Count();
            return View(saleProducts.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Category(int getType)
        {
            //Type = 0 lay tat ca san pham
            if (getType == 0)
            {
                IEnumerable<ProductType> listTypeM = productTypeDAO.getListM();
                IEnumerable<ProductType> listTypeF = productTypeDAO.getListF();
                IEnumerable<ProductType> listTypeK = productTypeDAO.getListK();
                ViewBag.listTypeM = listTypeM;
                ViewBag.listTypeF = listTypeF;
                ViewBag.listTypeK = listTypeK;
                ViewBag.countM = productDAO.ProductCountM();
                ViewBag.countF = productDAO.ProductCountF();
                ViewBag.countK = productDAO.ProductCountK();
            } 
           
            else if (getType == 1)
            {
                //Type == 1 Lay san pham khuyen mai
                IEnumerable<ProductType> listTypeM = productTypeDAO.getListM();
                IEnumerable<ProductType> listTypeF = productTypeDAO.getListF();
                IEnumerable<ProductType> listTypeK = productTypeDAO.getListK();
                ViewBag.listTypeM = listTypeM;
                ViewBag.listTypeF = listTypeF;
                ViewBag.listTypeK = listTypeK;
                int[] productGenderCount = productDAO
                    .getProductCountByCategoryGender(productDAO.getSaleProducts());
                ViewBag.countM = productGenderCount[0];
                ViewBag.countF = productGenderCount[1];
                ViewBag.countK = productGenderCount[2];
            }
            ViewBag.getType = getType;
            
            return PartialView();
        }

        public ActionResult FindProduct(string id,int? page, int pageSize = 9)
        {

            int count = productDAO.findProductCount(id);
            int pageNum = (page ?? 1);
            ViewBag.countAll = count;
            ViewBag.id = id;
            ViewBag.itemshow = pageSize;
            IEnumerable<Product> listPro = productDAO.findProduct(id, count);
            return View(listPro.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

clothesWebSite/Views/Clothes/AllPost.cshtml
@{
    ViewBag.Title = "AllPost";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item active">Blog listing</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <!--
                *** LEFT COLUMN ***
                _________________________________________________________
                -->
                <div id="blog-listing" class="col-lg-9">
                    <div class="box">
                        <h1>Blog category name</h1>
                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</p>
                    </div>
                    <!-- post-->
                    @foreach (var item in ViewBag.listPost)
                    {
                        string img = "post_" + item.post_id + "_1.jpg";
                <div class="post">
                    <h2><a href="@Url.Action("PostDeitail","Clothes",new{  id = item.post_id })">@item.title</a></h2>
                    <hr>
                    <p class="date-comments"><a href="@Url.Action("PostDeitail","Clothes",new{  id = item.post_id })"><i class="fa fa-calendar-o"></i> @item.last_update</a><a href="@Url.Action("PostDeitail","Clothes",new{  id = item.post_id })"><i class="fa fa-comment-o"></i> 8 Comments</a></p>
                    <div class="image"><a href="@Url.Action("PostDeitail","Clothes",new{  id = item.post_id })"><img src="~/img/news/@img" alt="Example blog post alt" class="img-fluid"></a></div>
                    <p class="intro">@item.content</p>
                    <p class="read-more"><a href="@Url.Action("PostDeitail","Clothes",new{  id = item.post_id })" class="btn btn-primary">Continue reading</a></p>
                </div>
                        <!-- post        -->
                    }

           
                    <div class="pager d-flex justify-content-between">
                        <div class="previous"><a href="#" class="btn btn-outline-primary">← Older</a></div>
                        <div class="next disabled"><a href="#" class="btn btn-outline-secondary disabled">Newer →        </a></div>
                    </div>
                </div>
                <!-- /.col-lg-9-->
                <!-- *** LEFT COLUMN END ***-->

                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Blog</h3>
                        </div>
                        <div class="card-body">
                            <ul class="nav flex-column nav-pills">
                                <li><a href="@Url.Action("AllPost","Clothes")" class="nav-link">About us</a></li>
                                <li><a href="@Url.Action("AllPost","Clothes")" class="nav-link active">Fashion</a></li>
                                <li><a href="@Url.Action("AllPost","Clothes")" class="nav-link">News and gossip</a></li>
                                <li><a href="@Url.Action("AllPost","Clothes")" class="nav-link">Design</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><a href="#"><img src="img/banner.jpg" alt="sales 2014" class="img-fluid"></a></div>
                </div>
            </div>
        </div>
    </div>
</div>

clothesWebSite/Views/Clothes/AllProduct.cshtml
@using clothesWebSite.Models
@using clothesWebSite.DAO;
@using PagedList.Mvc;
@model PagedList.PagedList<Product>
@{
    ViewBag.Title = "AllProduct";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item active">Product</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-9">
                    <div class="box">
                        <h1>Product</h1>
                        <p>Welcome to our Website hope you enjoy it and can get your favorite one.</p>
                    </div>
                    <div class="box info-bar">
                        <div class="row">
                            <div class="col-md-12 col-lg-4 products-showing">Showing <strong>12</strong> of <strong>25</strong> products</div>
                            <div class="col-md-12 col-lg-7 products-number-sort">
                                <form class="form-inline d-block d-lg-flex justify-content-between flex-column flex-md-row">
                                    <div class="products-number">
                                        <strong>Show</strong>
                                        <a href="@Url.Action("AllProduct", new {pageSize = 12 })" class="btn btn-outline-secondary btn-sm">12</a>
                                        <a href="@Url.Action("AllProduct", new {pageSize = 24 })" class="btn btn-outline-secondary btn-sm">24</a>
                                        <a href="@Url.Action("AllProduct", new {pageSize = ViewBag.countAll })" class="btn btn-outline-secondary btn-sm">All</a>
                                        @* <a href="@Url.Action("ProductSale", new {ItemShow = ViewBag.itemCount })" class="btn btn-outline-secondary btn-sm">All</a>*@
                                        <span>products</span>
                                    </div>
                                    <div class="products-sort-by mt-2 mt-lg-0">
                                        <strong>Sort by</strong>
                                        <select name="sort-by" class="form-control" id="SelectOption">
                                            <option value="null">
                                                Default
                                            </option>
                                            <option value="Price">
                                                <a href="/all-product?sort=price&pageSize=@ViewBag.itemshow">Price</a>
                                            </option>
                                            <option value="Date">
                                                <a href="/all-product?sort=date&pageSize=@ViewBag.itemshow">Date</a>
                                            </option>
                                            <option value="Name">
                                                <a href="/all-product?sort=name&pageSize=@ViewBag.itemshow">Name</a>
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="row products">
                        @foreach (var item in Model)
                        {


                            <div class="col-lg-4 col-md-6">
                                <div class="product">
                                    <div class="flip-container">
                                        <div class="flipper">
                                            <div class="front"><a href="@Url.Action("ProductDetail","Clothes", new{ id = item.product_id})"><img src="~/img/product/@item.image_name" alt="" class="img-fluid"></a></div>
                                        </div>
                                    </div><a href="@Url.Action("ProductDetail","Clothes", new{ id = item.product_id})" class="invisible"><img src="~/img/product/@item.image_name" alt="" class="img-fluid"></a>
                                    <div class="text">
                                        <h3><a href="@Url.Action("ProductDetail","Clothes", new{ id = item.product_id})">@item.product_name</a></h3>
                                        <p class="price">
                                            @if (ProductDAO.isSaleProduct(item))
                                            {
                                                <del>$@item.sale_price</del><text>$</text>@(item.sale_price - ProductDAO.getSalePrice(item))
                                            }
                                            else
                                            {
                                                @("$" + item.sale_price)
                                            }
                                        </p>
                                    </div>
                                    <!-- /.text-->
                                    @if (ProductDAO.isHotProduct(item))
                                    {
                                        <div class="ribbon new">
                                            <div class="theribbon">NEW</div>
                                            <div class="ribbon-background"></div>
                                        </div>
                                    }
                                    @if (ProductDAO.isSaleProduct(item))
                                    {
                                        <div class="ribbon sale">
                                            <div class="theribbon">SALE</div>
                                            <div class="ribbon-background"></div>
                                        </div>
                                    }
                                    <!-- /.ribbon-->
                                </div>
                                <!-- /.product            -->
                            </div>
                        }

                        @* Page @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount;*@
                        <div class="pages col-12">
                            @*<p class="loadMore"><a href="#" class="btn btn-primary btn-lg"><i class="fa fa-chevron-down"></i> Load more</a></p>*@
                            <div class="my-pagination">
                                @Html.PagedListPager(Model, Page => Url.Action("AllProduct", new { Page = Page,sort = ViewBag.sort, pageSize = ViewBag.itemshow }))
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.col-lg-9-->
                <div class="col-lg-3">
                    <!--
                    *** MENUS AND FILTERS ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 card-title">Categories</h3>
                        </div>
                        @Html.Action("Category", new { GetType = 0 })

                    </div>
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 card-title">Brands <a href="#" class="btn btn-sm btn-danger pull-right"><i class="fa fa-times-circle"></i> Clear</a></h3>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Armani  (10)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Versace  (12)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Carlo Bruni  (15)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> Jack Honey  (14)
                                        </label>
                                    </div>
                                </div>
                                <button class="btn btn-default btn-sm btn-primary"><i class="fa fa-pencil"></i> Apply</button>
                            </form>
                        </div>
                    </div>
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 card-title">Colours <a href="#" class="btn btn-sm btn-danger pull-right"><i class="fa fa-times-circle"></i> Clear</a></h3>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"><span class="colour white"></span> White (14)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"><span class="colour blue"></span> Blue (10)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"><span class="colour green"></span>  Green (20)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"><span class="colour yellow"></span>  Yellow (13)
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"><span class="colour red"></span>  Red (10)
                                        </label>
                                    </div>
                                </div>
                                <button class="btn btn-default btn-sm btn-primary"><i class="fa fa-pencil"></i> Apply</button>
                            </form>
                        </div>
                    </div>
                    <!-- *** MENUS AND FILTERS END ***-->
                    <div class="banner"><a href="#"><img src="img/banner.jpg" alt="sales 2014" class="img-fluid"></a></div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    document.getElementById('SelectOption').addEventListener('change', function () {
        val = $("#SelectOption").val();

        console.log(val)
        if (val === 'Date') {
            window.open('/all-product?sort=date&pageSize=@ViewBag.itemshow', '_self');
        }
        if (val === 'Price') {
            window.open('/all-product?sort=price&pageSize=@ViewBag.itemshow', '_self');
        }
        if (val === 'Name') {
            window.open('/all-product?sort=name&pageSize=@ViewBag.itemshow', '_self');
        }
    });
</script>

clothesWebSite/Views/Clothes/Category.cshtml
<div class="card-body">
    <ul class="nav nav-pills flex-column category-menu">
        <li>
            <a href="" class="nav-link">Men <span class="badge badge-secondary">@ViewBag.countM</span></a>
            <ul class="list-unstyled">
                @foreach (var item in ViewBag.listTypeM)
                {
                    <li><a href="@Url.Action("ProductCategoty","Clothes", new{ id = item.type_id, GetType = ViewBag.getType})" class="nav-link">@item.type_name</a></li>
                }
            </ul>
        </li>
        <li>
            <a href="" class="nav-link active">Ladies  <span class="badge badge-light">@ViewBag.countF</span></a>
            <ul class="list-unstyled">
                @foreach (var item in ViewBag.listTypeF)
                {
                <li><a href="@Url.Action("ProductCategoty","Clothes", new{ id = item.type_id, GetType = ViewBag.getType})" class="nav-link">@item.type_name</a></li>
                }
            </ul>
        </li>
        <li>
            <a href="" class="nav-link">Kids  <span class="badge badge-secondary">@ViewBag.countK</span></a>
            <ul class="list-unstyled">
                @foreach (var item in ViewBag.listTypeK)
                {
                <li><a href="@Url.Action("ProductCategoty","Clothes", new{ id = item.type_id, GetType = ViewBag.getType})" class="nav-link">@item.type_name</a></li>
                }
            </ul>
        </li>
    </ul>
</div>

clothesWebSite/Views/Clothes/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>test</h2>
@ViewBag.test